---
- name: get java version
  shell:   "java -version 2>&1"
  register: java_version_result
  changed_when: false

- name: test java version
  fail:
    msg: "this installation of fedora requires java version {{ java_version }} or higher"
  when:  "'{{ java_version }}' not in java_version_result.stdout"

- name: add fcrepo user
  user:
    name:   "{{ fcrepo_user }}"
    shell:  "/bin/bash"

- name: get fedora checksum
  set_fact:
    fcrepo_checksum: "{{ fcrepo_checksum_algo }}:{{ item }}"
  with_url: "{{ fcrepo_checksum_url }}"

- name: get fedora
  get_url:
    url:      "{{ fcrepo_url }}"
    dest:     "{{ webapps_dir }}"
    checksum: "{{ fcrepo_checksum }}"
    owner:    "{{ fcrepo_user }}"
    group:    "{{ fcrepo_user }}"
  register: got_fedora
  notify: restart tomcat

- name: create fedora directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"
  with_items:
    - "{{ fcrepo_config_dir }}"
    - "{{ fcrepo_home }}"
    - "{{ fcrepo_log_dir }}"

- name: create tomcat service directory for additional configuration
  file:
    path: "/etc/systemd/system/tomcat.service.d"
    state: directory

- name: set fedora system properties
  template:
    src: "fcrepo.conf.j2"
    dest: "/etc/systemd/system/tomcat.service.d/fcrepo.conf"
  notify: restart tomcat

- name: configure fedora logging
  template:
    src:  "logback.xml.j2"
    dest: "{{ fcrepo_config_dir }}/logback.xml"
  notify: restart tomcat
